#Docker File

#1 : Build stage
FROM node:22-alpine

#Set working directory
WORKDIR /app

#Copy files
COPY package*.json ./

#Install Dependencies
RUN npm install


#Build the vite projecgt
COPY . .
RUN npm run build

#2 Server usign NGINX
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# If you have a custom Nginx config, COPY it here, e.g.:
# COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]