version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - "80:80"
    container_name: vite-frontend

  backend:
    build: ./server
    ports:
      - "3000:3000"
    container_name: node-backend
    environment:
      - NODE_ENV=production
